services:
  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    # image: homebridge/homebridge:2025-01-11
    restart: always
    network_mode: host
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./_data_homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "1024mb"
        max-file: "1"
