services:
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    security_opt:
      - no-new-privileges:true
    ports:
      - "{{ homelab_transmission_port }}:{{ homelab_transmission_port }}"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:{{ homelab_transmission_port }}/|| exit 1"]
      interval: 60s
      timeout: 60s
      retries: 3
    environment:
      - PUID={{ common_folder_user_uid | default(0) }}
      - PGID={{ common_folder_user_gid | default(0) }}
    labels:
        tsdproxy.enable: "true"
        tsdproxy.name: "transmission"
        tsdproxy.container_port: "{{ homelab_transmission_port }}"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data_transmission:/config
      {{ homelab_media_binds | to_nice_yaml(indent=6) | indent(6) }}
    restart: unless-stopped

  transmission-rss:
    image: 0x3654/transmission-rss:latest
    container_name: transmission-rss
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID={{ common_folder_user_uid | default(0) }}
      - PGID={{ common_folder_user_gid | default(0) }}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data_transmission-rss:/etc/transmission-rss
      - ./transmission-rss.conf:/etc/transmission-rss.conf
    ports:
      - "444:443"
    restart: unless-stopped
    depends_on:
      - transmission

  torrserver:
    image: ghcr.io/yourok/torrserver:latest
    container_name: torrserver
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID={{ common_folder_user_uid | default(0) }}
      - PGID={{ common_folder_user_gid | default(0) }}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data_torrserver:/opt/ts
    ports:
      - "{{ homelab_torrserverport }}:{{ homelab_torrserverport }}"
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "torrserver"
      tsdproxy.container_port: "{{ homelab_torrserverport }}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:{{ homelab_torrserverport }} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3